name: "Prettier Code Style Check"

on:
  pull_request:
    branches:
      - "main"

jobs:
  style-check:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm install

      - run: npx prettier --check --ignore-unknown .
